spring.application.name=ClinicaOdontologica

spring.datasource.url=jdbc:postgresql://ep-patient-pond-b5wvbq2q-pooler.c-7.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_qzOd16FKcVat&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qzOd16FKcVat&ssl
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false